export const postsConstants = {
  GET_ALL_POSTS_REQUEST: 'GET_ALL_POSTS_REQUEST',
  GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
  GET_ALL_POSTS_FAILED: 'GET_ALL_POSTS_REQUEST',

  ADD_POSTS_REQUEST: 'ADD_POSTS_REQUEST',
  ADD_POSTS_SUCCESS: 'ADD_POSTS_SUCCESS',
  ADD_POSTS_FAILED: 'ADD_POSTS_FAILED',

  REMOVE_POSTS_REQUEST: 'REMOVE_POSTS_REQUEST',
  REMOVE_POSTS_SUCCESS: 'REMOVE_POSTS_SUCCESS',
  REMOVE_POSTS_FAILED: 'REMOVE_POSTS_FAILED',

  SEARCH_POSTS_REQUEST: 'SEARCH_POSTS_REQUEST',
  SEARCH_POSTS_SUCCESS: 'SEARCH_POSTS_SUCCESS',
  SEARCH_POSTS_FAILED: 'SEARCH_POSTS_FAILED',

  SET_RANGE_REQUEST: 'SET_RANGE_REQUEST',
  SET_RANGE_SUCCESS: 'SET_RANGE_SUCCESS',
  SET_RANGE_FAILED: 'SET_RANGE_FAILED',

  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILED: 'GET_USERS_FAILED'
}
