export const postsConstants = {
  GET_ALL_POSTS_REQUEST: 'GET_ALL_POSTS_REQUEST',
  GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
  GET_ALL_POSTS_FAILED: 'GET_ALL_POSTS_REQUEST',

  ADD_POSTS_REQUEST: 'ADD_POSTS_REQUEST',
  ADD_POSTS_SUCCESS: 'ADD_POSTS_SUCCESS',
  ADD_POSTS_FAILED: 'ADD_POSTS_FAILED',

  EDIT_POSTS_REQUEST: 'EDIT_POSTS_REQUEST',
  EDIT_POSTS_SUCCESS: 'EDIT_POSTS_SUCCESS',
  EDIT_POSTS_FAILED: 'EDIT_POSTS_FAILED',

  REMOVE_POSTS_REQUEST: 'REMOVE_POSTS_REQUEST',
  REMOVE_POSTS_SUCCESS: 'REMOVE_POSTS_SUCCESS',
  REMOVE_POSTS_FAILED: 'REMOVE_POSTS_FAILED',

  SEARCH_POSTS_REQUEST: 'SEARCH_POSTS_REQUEST',
  SEARCH_POSTS_SUCCESS: 'SEARCH_POSTS_SUCCESS',
  SEARCH_POSTS_FAILED: 'SEARCH_POSTS_FAILED',

  SET_PAGE_REQUEST: 'SET_PAGE_REQUEST',
  SET_PAGE_SUCCESS: 'SET_PAGE_SUCCESS',
  SET_PAGE_FAILED: 'SET_PAGE_FAILED',

  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILED: 'GET_USERS_FAILED',

  SET_USER_REQUEST: 'SET_USER_REQUEST',
  SET_USER_SUCCESS: 'SET_USER_SUCCESS',
  SET_USER_FAILED: 'SET_USER_FAILED'
}
